import Footer from './Componet01/views/Footer/Footer'
import Navbar from './Componet01/views/Navbar'
import TopLabel from './Componet01/views/TopLabel'

import './globals.css'
import { Maven_Pro } from 'next/font/google'

const maven = Maven_Pro({ 
  subsets: ['latin'], 
  weight:['400','500','600',"600","800","900"]
})

export const metadata = {
  title: 'Saud E-Commerece Dine Market',
  description: 'Generated by Saud Ahmed Sarki',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={maven.className}>
          <div className='overflow-hidden w-screen'>
            <TopLabel/>
          </div>
        <main className="max-w-7xl mx-auto px-4 md:px-10">
          
          {/* <Header/> */}
          <Navbar/>
          <div className=' min-h-screen'>
            {children}
          </div>
          
          <Footer/>
        </main>
        
      </body>
    </html>
  )
}

